language: cpp
sudo: required
services:
  - docker

script:
  - "/bin/true"

before_deploy:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build . -t screenly/screenly-webview-build
  - docker run --rm -t  --name screenly-webview-build -e VERSION=$TRAVIS_TAG -v $TRAVIS_BUILD_DIR:/Screenly-webview  screenly/screenly-webview-build

deploy:
  provider: releases
  api_key:
    secure: secure: uNFv3HpZEr6HIPBxD0KJnoEtS0uGcIP1z0mOXn0VbQxKrSIX9D2W1QZ40+u9wV8viEOgcL7c2o9UD4kFY3jLG3sjdUVWhoZ0hkb2QKbGUQp66gf3mRm1VWjwHHyd4E5sZEByrn4DksFMWoaD7S5QDWmacpgTfY2GQ1KVHB+dCzSGU++ejTIaDWgeKguXc1u9mH3/XbSfFdh3MwlG9zwH7CRJa761FmVzn7G5q/4JiHzeGFuOVPo/u0JfpO70Ctgt4UVNLhi+hpz6O6Hg+Zpp6O913rv040653PQjr7mFQZtSPAYmrO98Qu2SVdOd7BKRWESA/dP+n3FNDBstvJQWdwM+Ivy6szhgbRVyRq9xTcUrJibZe8CMEaRuMR2cLPKmgs+XNuMm4AzsfEmyzlsHfsHB108+uJFUPNleXBYVdvA1tn7z7SIT8dc1QgTcJi9wf1gS2Xu3xqqKJZYIlyrXIFJt0jzN93UktrmOdf5I7jHV9BdIpQbRwU31vrF2hnjg3BxmGzDeA2xS+UEnJNk8JT3SxaYwSIjea/ZNDJ8VlxXi9hN9PuVeXJ9/bvwypfUqVFgAdrM/84TIj6c/KNSDaUvQD6odhmR8zbw1aERSi+tSO2ECPxGfpbbvcqPoTekVgYLCXMqLjlp/BWAzzwL2o/oYB/5fnfkvEcGRSiMkovk=
  file: screenly-webview-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    repo: Screenly/ScreenlyOSE-WebView
    tags: true
